2023-02-05 05:1729 DEBUG Logger Initialized
2023-02-05 08:5011 DEBUG Logger Initialized
2023-02-05 09:4701 DEBUG Logger Initialized
2023-02-05 10:3641 DEBUG Logger Initialized
2023-02-05 10:3649 DEBUG Logger Initialized
2023-02-05 10:3820 DEBUG Logger Initialized
2023-02-05 10:3936 DEBUG Logger Initialized
2023-02-05 10:4124 DEBUG Logger Initialized
2023-02-05 10:4247 DEBUG Logger Initialized
2023-02-05 10:4722 DEBUG Logger Initialized
2023-02-05 10:4917 DEBUG Logger Initialized
2023-02-05 10:5105 DEBUG Logger Initialized
2023-02-05 10:5331 DEBUG Logger Initialized
2023-02-05 10:5424 DEBUG Logger Initialized
2023-02-05 11:1834 DEBUG Logger Initialized
2023-02-05 11:1911 DEBUG Logger Initialized
2023-02-05 11:2048 DEBUG Logger Initialized
2023-02-05 11:2107 ERROR __Error__'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 92, in suspect_faces
    user_id = user_json_data["user_id"]
TypeError: 'NoneType' object is not subscriptable
2023-02-05 11:2251 DEBUG Logger Initialized
2023-02-05 11:2843 DEBUG Logger Initialized
2023-02-05 11:2847 DEBUG Logger Initialized
2023-02-05 11:3109 DEBUG Logger Initialized
2023-02-05 11:4151 DEBUG Logger Initialized
2023-02-05 11:5342 DEBUG Logger Initialized
2023-02-05 11:5940 DEBUG Logger Initialized
2023-02-05 12:0103 ERROR __Error__result.html
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 139, in suspect_faces
    return render_template("result.html", result=final_response)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: result.html
2023-02-05 12:0351 DEBUG Logger Initialized
2023-02-05 12:0359 ERROR __Error__list index out of range
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 91, in suspect_faces
    top_matched_numbers = request.form.getlist('top_matched_numbers')[0]
IndexError: list index out of range
2023-02-05 12:0912 DEBUG Logger Initialized
2023-02-05 12:0944 ERROR __Error__result.html
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 139, in suspect_faces
    return render_template("result.html", result=final_response)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: result.html
2023-02-05 12:1041 DEBUG Logger Initialized
2023-02-05 12:1110 ERROR __Error__result.html
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 139, in suspect_faces
    return render_template("result.html", result=final_response)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: result.html
2023-02-05 12:1139 DEBUG Logger Initialized
2023-02-05 12:1631 DEBUG Logger Initialized
2023-02-05 12:1958 DEBUG Logger Initialized
2023-02-05 12:2210 DEBUG Logger Initialized
2023-02-05 12:2251 ERROR __Error__Encountered unknown tag 'endfor'.
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 139, in suspect_faces
    return render_template("matched.html", result=final_response)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/templates/matched.html", line 28, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'.
2023-02-05 12:2656 DEBUG Logger Initialized
2023-02-05 12:2756 DEBUG Logger Initialized
2023-02-05 12:2828 ERROR __Error__too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 139, in suspect_faces
    return render_template("matched.html", result=final_response)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/templates/matched.html", line 15, in top-level template code
    {% for key, values in result %}
ValueError: too many values to unpack (expected 2)
2023-02-05 12:2957 DEBUG Logger Initialized
2023-02-05 12:3027 ERROR __Error__too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 139, in suspect_faces
    return render_template("matched.html", result=final_response)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/amit/anaconda3/envs/venv_xfactor_image_matching/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/templates/matched.html", line 15, in top-level template code
    <!--  {% for key, values in result %}-->
ValueError: too many values to unpack (expected 2)
2023-02-05 12:5103 DEBUG Logger Initialized
2023-02-05 12:5132 ERROR __Error__too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/amit/afghani_root_folder/ElintData/PoliceHackathon/ImageMatching/police_hackathon_suspect_image_match/Scripts/xfactor_main.py", line 138, in suspect_faces
    for k, v in final_response:
ValueError: too many values to unpack (expected 2)
